# Generated by Django 5.2.3 on 2025-06-16 23:17

import django.core.validators
import django.db.models.deletion
import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to=subjects.models.document_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='file')),
                ('file_type', models.CharField(max_length=10, verbose_name='file type')),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes', verbose_name='file size')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='page count')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subjects.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
