# Generated by Django 5.2.3 on 2025-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_add_uploaded_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('study_material', 'Study Material'), ('exam', 'Exam')], default='study_material', max_length=20, verbose_name='document type'),
        ),
    ]
