# Generated by Django 5.2.3 on 2025-06-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_topic_document_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subjects.topic', verbose_name='topic'),
            preserve_default=False,
        ),
    ]
