# Generated by Django 5.2.3 on 2025-06-17 16:51

from django.db import migrations, models


def create_default_topics_and_assign_documents(apps, schema_editor):
    """
    Create a default topic for each subject if it doesn't have any topics,
    and assign all documents with null topics to their subject's default topic.
    """
    Subject = apps.get_model('subjects', 'Subject')
    Topic = apps.get_model('subjects', 'Topic')
    Document = apps.get_model('subjects', 'Document')

    # Get all subjects
    for subject in Subject.objects.all():
        # Check if the subject has any topics
        topics = Topic.objects.filter(subject=subject)

        if not topics.exists():
            # Create a default topic for the subject
            default_topic = Topic.objects.create(
                subject=subject,
                name="General",
                description="Default topic for general documents"
            )
        else:
            # Use the first topic as the default
            default_topic = topics.first()

        # Assign all documents with null topics to the default topic
        Document.objects.filter(subject=subject, topic__isnull=True).update(topic=default_topic)


def reverse_migration(apps, schema_editor):
    """
    No need to reverse this migration as it's a data migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_document_topic'),
    ]

    operations = [
        migrations.RunPython(
            create_default_topics_and_assign_documents,
            reverse_migration
        ),
        migrations.AlterField(
            model_name='document',
            name='topic',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='documents',
                to='subjects.topic',
                verbose_name='topic'
            ),
        ),
    ]
